version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "sensor_data:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  # producer:
  #   build: ./producer
  #   environment:
  #     KAFKA_BROKER: kafka:9092
  #   depends_on:
  #     - kafka

  # consumer:
  #   build: ./consumer
  #   environment:
  #     KAFKA_BROKER: kafka:9092
  #   depends_on:
  #     - kafka